### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by bclarke25** [asu-cis-capstone/schoolfly#12]
You guys sold me on schoolfly. 
schoolfly.co is registered. 

I took a crack at a logo. Travis, feel free to take a crack at it too.

http://schoolfly.co/graphics/schoolfly_bg.png

http://schoolfly.co/graphics/schoolfly_tran.png

http://schoolfly.co/graphics/schoolfly_img.png

**Comment by tjlindahl** [comment]
I was already thinking of doing something with the paper airplane, and I love the way your logo looks. Let's stick with that!
